# Generated by Django 5.1.6 on 2025-07-09 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(default='admin_profile_pics/default_admin.jpg', upload_to='admin_profile_pics/'),
        ),
    ]
